import React, { useEffect, useState, useRef, useMemo } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Heart, Share2, Mic, Send, ChevronLeft, Clock, X } from 'lucide-react';
import { synthesizeStory } from '../../../services/newsApi'; 
import './NewsContent.css';

interface NewsContentProps {
    sidebarOpen: boolean;
    onAskQuestion?: (
        question: string,
        article: {
            title: string;
            imageUrl?: string;
            description?: string;
            publishedAt?: string;
            releasedMinutes?: number;
            all_sources?: { title: string; url: string; source: string; domain_url?: string }[];
            url?: string;
            slug: string;
            path: string;
        }
    ) => void;
}

type ArticleViewModel = {
  title: string;
  description?: string;
  imageUrl?: string;
  releasedMinutes?: number;
    publishedAt?: string;
  source?: string;
  url?: string;
  all_sources?: { title: string; url: string; source: string; domain_url?: string }[];
};

type SourceItem = {
    title: string;
    url: string;
    source: string;
    domain_url?: string;
    description?: string;
    citation_index?: number;
};

const fallbackArticle: ArticleViewModel = {
  title: 'No Article Selected',
  description: "Please select an article from the Discover feed.",
  imageUrl: '',
  releasedMinutes: 0,
  source: 'AskVox News',
};

// Helper for favicon
const getFaviconUrl = (link?: string, domainUrl?: string) => {
    if (domainUrl) {
         try { return `https://www.google.com/s2/favicons?domain=${new URL(domainUrl).hostname}&sz=32`; } catch {}
    }
    if (link) {
        try { return `https://www.google.com/s2/favicons?domain=${new URL(link).hostname}&sz=32`; } catch {}
    }
    return '';
};

const getHostname = (link?: string) => {
    if (!link) return '';
    try {
        return new URL(link).hostname.replace(/^www\./, '');
    } catch {
        return '';
    }
};

const NewsContent: React.FC<NewsContentProps> = ({ sidebarOpen, onAskQuestion }) => {
    const navigate = useNavigate();
    const location = useLocation();
    const article: ArticleViewModel = (location.state?.article as ArticleViewModel) || fallbackArticle;
    const [followupText, setFollowupText] = useState<string>("");
    const currentPath = location.pathname || "";
    const slugFromPath = currentPath.split("/").pop() || "article";
  
  const formatRelative = (publishedAt?: string, mins?: number) => {
      if (publishedAt) {
          const hasTzOffset = /[+-]\d{2}:?\d{2}$/.test(publishedAt);
          const cleanIso = publishedAt.replace(' ', 'T') + (publishedAt.includes('Z') || hasTzOffset ? '' : 'Z');
          const time = new Date(cleanIso).getTime();
          if (!isNaN(time)) {
              const diffMs = Date.now() - time;
              const diffMins = Math.max(0, Math.round(diffMs / 60000));
              const rtf = new Intl.RelativeTimeFormat('en', { numeric: 'auto' });
              if (diffMins < 60) return rtf.format(-diffMins, 'minute');
              const diffHours = Math.round(diffMins / 60);
              if (diffHours < 24) return rtf.format(-diffHours, 'hour');
              const diffDays = Math.round(diffHours / 24);
              if (diffDays < 7) return rtf.format(-diffDays, 'day');
              return new Date(time).toLocaleDateString('en-SG', { year: 'numeric', month: 'short', day: 'numeric' });
          }
      }
      if (mins === undefined || isNaN(mins)) return 'Just now';
      if (mins === 0) return 'Just now';
      if (mins < 60) return `${mins}m ago`;
      return `${Math.floor(mins / 60)}h ago`;
  };
  const releasedLabel = formatRelative(article.publishedAt, article.releasedMinutes);
    const handleFollowupSend = () => {
        const trimmed = followupText.trim();
        if (!trimmed) return;
        if (!onAskQuestion) return;
        onAskQuestion(trimmed, {
            title: article.title,
            imageUrl: article.imageUrl,
            description: article.description,
            publishedAt: article.publishedAt,
            releasedMinutes: article.releasedMinutes,
            all_sources: article.all_sources,
            url: article.url,
            slug: slugFromPath,
            path: currentPath,
        });
        setFollowupText("");
    };

    const handleFollowupKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
        if (e.key === "Enter") {
            e.preventDefault();
            handleFollowupSend();
        }
    };

    const [fullText, setFullText] = useState<string>("");  // Text generated by AI
    const [citationSources, setCitationSources] = useState<SourceItem[]>([]);  // Sources for citations
    const [listSources, setListSources] = useState<SourceItem[]>([]);  // Sources list for UI
  const [isLoading, setIsLoading] = useState<boolean>(true);
    const [isSourcesOpen, setIsSourcesOpen] = useState<boolean>(false);
  
  const hasFetched = useRef(false);

  useEffect(() => {
    if (hasFetched.current) return; // Prevent duplicate fetch if already loaded
    if (!article.title) { setIsLoading(false); return; }

    hasFetched.current = true; 
    setIsLoading(true);

    const loadContent = async () => {
        // If we passed sources from the previous screen, allow rendering them immediately while loading text
        if (article.all_sources) {
            setListSources(article.all_sources);  // Use passed sources from the article
        }

        // Fetch the content (AI synthesis)
        const data = await synthesizeStory(article.title, article.all_sources); // Pass sources to backend
        setFullText(data.content);
        // If backend returns better sources (validated), update them
        if (data.sources && data.sources.length > 0) {
            setCitationSources(data.sources as SourceItem[]);
            if (!article.all_sources || article.all_sources.length === 0) {
                setListSources(data.sources as SourceItem[]);
            }
        }
        setIsLoading(false);
    };

    loadContent();
    }, [article.title, article.all_sources]); // Trigger on title or sources change

    const sourcesForDisplay = useMemo(() => {
        if (listSources && listSources.length > 0) return listSources;
        return citationSources;
    }, [listSources, citationSources]);

  // --- 🟢 ADVANCED PARSER FUNCTION ---
  const renderStyledContent = (text: string) => {
    if (!text) return null;

    // 1. Process Citations First: Turn [1] into formatted markers inside the string
    // This is tricky in React, so we process blocks first.

    const lines = text.split('\n');
    const elements: React.ReactNode[] = [];
    let listBuffer: React.ReactNode[] = [];

    const sourcesForCitations = (citationSources.length > 0 ? citationSources : sourcesForDisplay) as SourceItem[];

    // Function to handle inline Bold **text** and citations like [1] or [implied from 1, 2]
    const processInline = (str: string) => {
        const parts = str.split(/(\*\*.+?\*\*|\[(?:implied from\s*)?\d+(?:\s*,\s*\d+)*\])/gi);
        return parts.map((part, i) => {
            if (part.startsWith('**') && part.endsWith('**')) {
                return <strong key={i}>{part.slice(2, -2)}</strong>;
            }
            if (/^\[(?:implied from\s*)?\d+(?:\s*,\s*\d+)*\]$/i.test(part)) {
                const implied = /^\[\s*implied from/i.test(part);
                const nums = part.match(/\d+/g) ?? [];
                if (nums.length === 0) return part;

                return (
                    <span key={i} style={{ whiteSpace: 'nowrap' }}>
                        {implied ? <span style={{ opacity: 0.75 }}>implied from </span> : null}
                        {nums.map((n, idx) => {
                            const num = parseInt(n, 10);
                            const src = Number.isFinite(num) ? sourcesForCitations[num - 1] : undefined;
                            const href = src?.url;
                            const title = src?.title || `Source ${n}`;
                            const pill = href ? (
                                <a
                                    key={`${i}-${n}-${idx}`}
                                    href={href}
                                    target="_blank"
                                    rel="noreferrer"
                                    className="citation-pill"
                                    title={title}
                                    onClick={(e) => e.stopPropagation()}
                                >
                                    {n}
                                </a>
                            ) : (
                                <span key={`${i}-${n}-${idx}`} className="citation-pill" style={{ opacity: 0.55, cursor: 'default' }}>
                                    {n}
                                </span>
                            );
                            return (
                                <React.Fragment key={`${i}-frag-${n}-${idx}`}>
                                    {pill}
                                    {idx < nums.length - 1 ? <span style={{ opacity: 0.7 }}>, </span> : null}
                                </React.Fragment>
                            );
                        })}
                    </span>
                );
            }
            return part;
        });
    };

    lines.forEach((line, index) => {
        const trimmed = line.trim();
        if (!trimmed) {
             if (listBuffer.length) {
                elements.push(<ul key={`list-${index}`}>{listBuffer}</ul>);
                listBuffer = [];
            }
            return;
        }

        // Headers
        if (trimmed.startsWith('### ')) {
            if (listBuffer.length) { elements.push(<ul key={`list-${index}`}>{listBuffer}</ul>); listBuffer = []; }
            elements.push(<h3 key={index}>{trimmed.replace('### ', '')}</h3>);
        } 
        else if (trimmed.startsWith('## ')) {
             if (listBuffer.length) { elements.push(<ul key={`list-${index}`}>{listBuffer}</ul>); listBuffer = []; }
            elements.push(<h3 key={index}>{trimmed.replace('## ', '')}</h3>);
        }
        // Bullet Points (* or -)
        else if (trimmed.startsWith('* ') || trimmed.startsWith('- ')) {
            const content = trimmed.slice(2);
            listBuffer.push(<li key={index}>{processInline(content)}</li>);
        }
        // Normal Paragraph
        else {
             if (listBuffer.length) { elements.push(<ul key={`list-${index}`}>{listBuffer}</ul>); listBuffer = []; }
             // Ignore "Briefing" titles if they appear as plain text
             if (!trimmed.toLowerCase().includes("briefing")) {
                 elements.push(<p key={index}>{processInline(trimmed)}</p>);
             }
        }
    });

    if (listBuffer.length) elements.push(<ul key="end-list">{listBuffer}</ul>);
    return elements;
  };

  return (
    <div className={`nc-main ${!sidebarOpen ? 'nc-sidebar-closed' : ''}`}>
        <div className="nc-article-container">
            <button className="nc-back-btn" onClick={() => navigate(-1)} style={{ position: 'relative', zIndex: 1000 }}>
                <ChevronLeft size={20} color="#FF951C" /> 
                <span>Back</span>
            </button>

            <header className="nc-header">
                <h1 className="nc-headline">{article.title}</h1>
                <div className="nc-meta-row">
                    <span className="nc-time">
                        <Clock size={14} style={{ marginRight: 4 }} /> 
                        {releasedLabel}
                    </span>
                    <button
                        className={`nc-sources-pill ${sourcesForDisplay.length === 0 ? 'nc-sources-pill--disabled' : ''}`}
                        onClick={() => setIsSourcesOpen(true)}
                        disabled={sourcesForDisplay.length === 0}
                        title={sourcesForDisplay.length === 0 ? 'No sources available' : 'View sources'}
                    >
                        <span className="nc-sources-pill__stack">
                            {sourcesForDisplay.slice(0, 4).map((src, idx) => (
                                <img
                                    key={`${src.url}-${idx}`}
                                    className="nc-sources-pill__icon"
                                    src={getFaviconUrl(src.url, src.domain_url)}
                                    alt=""
                                    onError={(e) => (e.currentTarget.style.display = 'none')}
                                />
                            ))}
                        </span>
                        <span className="nc-sources-pill__label">
                            {sourcesForDisplay.length > 0 ? `${sourcesForDisplay.length} sources` : 'Sources'}
                        </span>
                    </button>
                    <div className="nc-actions">
                         <button className="nc-icon-btn"><Heart size={20} /></button>
                         <button className="nc-icon-btn"><Share2 size={20} /></button>
                    </div>
                </div>
            </header>

            <article className="nc-body">
                {article.imageUrl && (
                    <div className="nc-hero-image-wrapper">
                        <img
                            src={article.imageUrl}
                            alt={article.title}
                            className="nc-hero-image"
                        />
                    </div>
                )}
                {/* 🟢 AI CONTENT (Formatted) */}
                <div className="nc-extended-content ai-content">
                    {isLoading ? (
                         <div style={{ marginTop: '20px', opacity: 0.5 }}>
                            <p>Analyzing sources...</p>
                            <div className="nc-skeleton-line" style={{ width: '100%' }}></div>
                            <div className="nc-skeleton-line" style={{ width: '90%' }}></div>
                            <div className="nc-skeleton-line" style={{ width: '95%' }}></div>
                         </div>
                    ) : (
                        renderStyledContent(fullText)
                    )}
                </div>
            </article>

            {isSourcesOpen && (
                <div className="nc-sources-overlay" onClick={() => setIsSourcesOpen(false)}>
                    <div className="nc-sources-panel" onClick={(e) => e.stopPropagation()}>
                        <div className="nc-sources-panel__header">
                            <div className="nc-sources-panel__title">Sources</div>
                            <button
                                className="nc-sources-panel__close"
                                onClick={() => setIsSourcesOpen(false)}
                                aria-label="Close sources"
                            >
                                <X size={16} />
                            </button>
                        </div>
                        <div className="nc-sources-panel__count">
                            {sourcesForDisplay.length} sources
                        </div>
                        <div className="nc-sources-panel__list">
                            {sourcesForDisplay.map((src, idx) => (
                                <a
                                    key={`${src.url}-${idx}`}
                                    className="nc-source-item"
                                    href={src.url}
                                    target="_blank"
                                    rel="noreferrer"
                                >
                                    <img
                                        className="nc-source-item__favicon"
                                        src={getFaviconUrl(src.url, src.domain_url)}
                                        alt=""
                                        onError={(e) => (e.currentTarget.style.display = 'none')}
                                    />
                                    <div className="nc-source-item__content">
                                        <div className="nc-source-item__meta">
                                            <span className="nc-source-item__publisher">{src.source}</span>
                                            {getHostname(src.url) ? (
                                                <span className="nc-source-item__domain">{getHostname(src.url)}</span>
                                            ) : null}
                                        </div>
                                        <div className="nc-source-item__title">{src.title}</div>
                                        {src.description && (
                                            <div className="nc-source-item__snippet">{src.description}</div>
                                        )}
                                    </div>
                                </a>
                            ))}
                        </div>
                    </div>
                </div>
            )}

            {/* Chat Bar */}
            <div className="nc-chat-wrapper">
                <div className="nc-chat-bar">
                    <div className="nc-chat-input-group">
                        <span className="nc-paperclip-icon">📎</span>
                        <input
                          type="text"
                          placeholder="Ask follow-up questions..."
                          className="nc-chat-input"
                          value={followupText}
                          onChange={(e) => setFollowupText(e.target.value)}
                          onKeyDown={handleFollowupKeyDown}
                        />
                    </div>
                    <div className="nc-chat-actions">
                        <button className="nc-chat-icon"><Mic size={18} /></button>
                        <button className="nc-send-btn" onClick={handleFollowupSend} disabled={!followupText.trim()}>
                          <Send size={16} fill="currentColor" />
                        </button>
                    </div>
                </div>
            </div>
      </div>
    </div>
  );
};

export default NewsContent;
